version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: /home/yunus/personal/prod/frontend/Dockerfile.dev
    ports:
     - "3000:3000"
    volumes:
     - /usr/app/node_modules
     - ./app
      